# Generated by Django 3.1 on 2020-08-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignassignment',
            name='upload_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='upload_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='submitassignment',
            name='submission_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timetablefile',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
