# Generated by Django 3.1 on 2020-08-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmindata',
            name='adminPin',
            field=models.IntegerField(default=0),
        ),
    ]
